language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.7"
  - "5.8.7-thr"
  - "5.8.8"
  - "5.8.9"
  - "5.10.0"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "5.32"
  - dev
  - blead
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
